### ISSUE TITLE
JDBC request fails with "WFLYJPA0060: Transaction is required to perform this operation (either use a transaction or extended persistence context)"

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/wildfly-datasources-galleon-pack#17]
Using the env vars:

```
  - name: POSTGRESQL_DATABASE
    valueFrom:
      secretKeyRef:
        key: database-name
        name: kitchensink-db
  - name: POSTGRESQL_USER
    valueFrom:
      secretKeyRef:
        key: database-user
        name: kitchensink-db
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: kitchensink-db
  - name: POSTGRESQL_DATASOURCE
    value: KitchensinkQuickstartDS
  - name: POSTGRESQL_SERVICE_HOST
    value: kitchensink-db
  - name: POSTGRESQL_SERVICE_PORT
    value: "5432"
```

The same application works when I'm using the env vars to install PostgreSQL driver provided by the WildFly S2I images:

```
  - name: DATASOURCES
    value: PGSQL
  - name: PGSQL_DATABASE
    valueFrom:
      secretKeyRef:
        key: database-name
        name: kitchensink-db
  - name: PGSQL_USERNAME
    valueFrom:
      secretKeyRef:
        key: database-user
        name: kitchensink-db
  - name: PGSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: database-password
        name: kitchensink-db
  - name: PGSQL_DRIVER
    value: postgres
  - name: PGSQL_JNDI
    value: java:jboss/datasources/KitchensinkQuickstartDS
  - name: PGSQL_JTA
    value: "false"
  - name: PGSQL_NONXA
    value: "true"
  - name: PGSQL_URL
    value: "jdbc:postgresql://kitchensink-db:5432/kitchensink"
```

At first glance, I'm missing the ability to configure JTA (and NONXA) attributes

* https://github.com/wildfly/wildfly-cekit-modules/blob/ce9b6c62a40b6f812955decb454bc1c9c344fb55/jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh#L461
* https://github.com/wildfly/wildfly-cekit-modules/blob/ce9b6c62a40b6f812955decb454bc1c9c344fb55/jboss/container/wildfly/launch/datasources/added/launch/datasource-common.sh#L379

I've not found which env vars I could use to configure it in either https://github.com/wildfly-extras/wildfly-datasources-galleon-pack/blob/master/src/main/resources/layers/standalone/postgresql-datasource/layer-spec.xml or https://github.com/wildfly-extras/wildfly-datasources-galleon-pack/blob/master/src/main/resources/layers/standalone/postgresql-driver/layer-spec.xml
